task_name: tuning
iter_name: model_16_001_4_drop04
img_data_path: data/train/training_images
mask_data_path: data/train/training_masks
img_test_data_path: data/test
n_folds: 5
data:
  img_ch: 1
  img_w: 768
  img_h: 768
net:
  net_model: UNet
  base: 16
  loss: dice_loss
  optimizer: Adam
  metrics:
  - dice_coeff_multilabel
  - dice_coeff_arteries
  - dice_coeff_veins
  - jaccard_coeff_multilabel
  - jaccard_coeff_arteries
  - jaccard_coeff_veins
  n_epoch: 300
  batch_s: 4
  learning_rate: 0.001
  dropout: true
  dropout_rate: 0.4
  normalization: false
  output_layers: 3
mean_metrics:
  Mean val_dice_coeff_multilabel: 0.5116723775863647
  Std val_dice_coeff_multilabel: 0.15435793238467466
  Mean val_dice_coeff_arteries: 0.38697636872529984
  Std val_dice_coeff_arteries: 0.24185289548325267
  Mean val_dice_coeff_veins: 0.6472731232643127
  Std val_dice_coeff_veins: 0.08322524330480746
  Mean val_jaccard_coeff_multilabel: 0.3783446401357651
  Std val_jaccard_coeff_multilabel: 0.1401157402955754
  Mean val_jaccard_coeff_arteries: 0.27602475732564924
  Std val_jaccard_coeff_arteries: 0.19768150622985267
  Mean val_jaccard_coeff_veins: 0.48874971866607664
  Std val_jaccard_coeff_veins: 0.09608339496848951
