task_name: tuning
iter_name: model_16_001_4_drop02
img_data_path: data/train/training_images
mask_data_path: data/train/training_masks
img_test_data_path: data/test
n_folds: 5
data:
  img_ch: 1
  img_w: 768
  img_h: 768
net:
  net_model: UNet
  base: 16
  loss: dice_loss
  optimizer: Adam
  metrics:
  - dice_coeff_multilabel
  - dice_coeff_arteries
  - dice_coeff_veins
  - jaccard_coeff_multilabel
  - jaccard_coeff_arteries
  - jaccard_coeff_veins
  n_epoch: 300
  batch_s: 4
  learning_rate: 0.001
  dropout: true
  dropout_rate: 0.2
  normalization: false
  output_layers: 3
mean_metrics:
  Mean val_dice_coeff_multilabel: 0.499951171875
  Std val_dice_coeff_multilabel: 0.1135364992714168
  Mean val_dice_coeff_arteries: 0.3497184231877327
  Std val_dice_coeff_arteries: 0.21711271319499442
  Mean val_dice_coeff_veins: 0.6595616698265075
  Std val_dice_coeff_veins: 0.07941890788453576
  Mean val_jaccard_coeff_multilabel: 0.36637732982635496
  Std val_jaccard_coeff_multilabel: 0.10152496808709248
  Mean val_jaccard_coeff_arteries: 0.2377135530114174
  Std val_jaccard_coeff_arteries: 0.17277711645155255
  Mean val_jaccard_coeff_veins: 0.5016647100448608
  Std val_jaccard_coeff_veins: 0.09370461139608363
