---
task_name: "task2"
iter_name: ""
load_weights_history: False
load_data: True
data_path: Lab3/CT/
img_data_path: Lab3/CT/Image/
mask_data_path: Lab3/CT/Mask/
sample: Im0_64.png
use_augmentation: True
binary: False
data:
  img_ch: 3
  img_w: 256
  img_h: 256
generator:
  rotation_range: 10
  width_shift_range: 0.1
  height_shift_range: 0.1
  zoom_range: 0.2
  horizontal_flip: True
  batch_s: 8
  shuffle: True
  seed: 313
net:
  net_model: UNet
  base: 8
  loss: categorical_crossentropy
  optimizer: Adam  
  metrics: dice_coeff
  n_epoch: 80
  batch_s: 8
  learning_rate: 0.0001
  dropout: True
  dropout_rate: 0.2
  normalization: True
  output_layers: 3
  step_per_epoch: 500
  validation_step: 200