---
task_name: "task1c"
iter_name: "_V" # "_A" 
load_weights_history: False
data_path: Lab1/Skin/
use_preloaded_data: True
data:
  img_ch: 1
  img_w: 128
  img_h: 128
net:
  net_model: VGG16 # AlexNet
  base: 8
  base_dense_1: 64
  base_dense_2: 0
  normalization: False
  spatial_drop: False
  spatial_drop_rate: 0
  loss: BinaryCrossentropy 
  optimizer: Adam  
  metrics: binary_accuracy
  n_epoch: 150
  batch_s: 8
  learning_rate: 0.00001
  dropout: False 
  dropout_rate: 0
  output_layers: 1