---
task_name: "task2"
iter_name: "_8"
load_weights_history: False
data_path: Lab1/Bone/
use_preloaded_data: True
data:
  img_ch: 1
  img_w: 128
  img_h: 128
net:
  net_model: VGG16
  base: 8
  base_dense_1: 64
  loss: BCE 
  optimizer: Adam  
  metrics: binary_accuracy
  n_epoch: 100
  batch_s: 8
  learning_rate: 0.00001
  dropout: False
  dropout_rate: 0.2
  output_layers: 1